import { Inter } from 'next/font/google'
import '../styles/globals.css'
import Navbar from '@/components/nav/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <main style={{minHeight:"calc(100vh - 48px)"}}>{children}</main>
        <footer style={{color:"black",background:"white",textAlign:"center",letterSpacing:"20px"}}>FOOTER</footer>
        </body>
    </html>
  )
}
